### PR TITLE
Implement FOV adjustment for Surround mode

### LINKED ISSUE #35: Option to adjust Horizontal FOV
So, I tested your app, and honestly it's the best one yet, I don't know why other video players can't even get a fraction of your power 😅.

My situation: I'm trying to play VR video (180 SBS) on an Nreal Air, basically equivalent to VR glasses with low FOV.

The "binocular" or camera view of your app is perfect for watching VR video, because we are not supposed to view the entire FOV of VR content in a smaller screen.

But the issue is that, often times the default viewport is not the best. A lot is getting horizontally "squished" view because it's too wide. Here is an illustration (green is the video, blue is the original viewport, red is the adjusted):

image

---

Other example, the ability to "zoom-in" like how you can zoom in Google Street view, but instead the horizontal & vertical zoom are adjustable independently.

### PR DESCRIPTION
**Pull request by ArsenicBismuth**
New feature to resolve #35 , allowing adjustment of the camera/viewport's FOV during surround mode.

Everything is controllable via mouse wheel with modifiers:

- `Wheel`: Zoom in/out
- `Shift` + `Wheel`: Adjust horizontal FOV
- `Ctrl` + `Wheel`: Adjust vertical FOV

Note: Due to how the screen size is calculated internally, the vertical FOV adjustment will also affect the horizontal FOV.

Sample data is 3D 180 SBS: https://drive.google.com/drive/folders/1c0iI1wGNPUJkq3qnj7LRwjLv3a46NR-g

Default:

image

Wider horizontal FOV:

image

Narrower horizontal FOV:

image

Wider vertical FOV:

image

### CODE REVIEW

**Comment by marlam** [comment]
I'm not sure about this.

For glasses such as the one mentioned in #35, there are actually correct HVOF and VFOV settings that should be used. If the glasses are supported by OpenVR/SteamVR, you can just build Bino with QVR and get the correct settings automatically (and get head tracking too if the glasses support it).

The default VFOV of 50 is something that works well on typical displays, and it's used by VLC too. The HFOV derived from it ensures a distortion-free view. So when you adjust one or the other, you basically only introduce distortions.

**Comment by ArsenicBismuth** [comment]
> VFOV of 50 is something that works well on typical displays

I mean this is why it's just the extra knob to adjust. For example Xreal Air DIAGONAL FOV is 46, so lower for the horizontal, and definitely even much lower for vertical. Point is, it's not 50.

For a speciality software, why not? I'm using your app instead of VLC specifically because VLC gives no control to the user. If people want VLC experience they can use VLC.

And even if you're not a fan of the horizontal adjustment, the "zoom" is very nice to have.

---

Again the default is still 50, the rest is user preference. If they prefer certain FOV despite the distortion you talk about (I don't see any as long as it's not extreme), then let them be.

**Comment by ArsenicBismuth** [comment]
Also I think reducing the FOV (which is the main poin) won't cause any distortion, if that's your problem. Because you're seeing the "sphere" with smaller window.

Unlike increasing FOV where you're trying to cram higher FOV content into smaller device FOV.

**Comment by marlam** [comment]
OK, I can see the usefulness of zooming.

So in a first step, let's introduce zooming by adjusting the vertical field of view. This should not introduce any distortions as long as the horizontal FOV is computed from the vertical correctly (i.e. without depending on the viewport size).

This is implemented in commit [1e59d93](https://github.com/marlam/bino/commit/1e59d93ce0ff27f05b074402be6f3a6cab25a18d) in a way that also allows adjustment via command line and via scripting, and a reset by hitting `Z`.

Are you ok with that first part?

**Comment by marlam** [comment]
OK, some people want to tinker with horizontal field of view even though this will almost certainly not give physically plausible results ;)

In commit [30e7eb4](https://github.com/marlam/bino/commit/30e7eb4d3d158d754ebb4544e11e5a3c6766d032), this is implemented by adjusting the assumed aspect ratio of the material - the value 2:1 is always the correct one, but adjusting it might help with some glasses as in issue #35.

This should now cover all the uses cases, right?

**Comment by ArsenicBismuth** [comment]
What's the point of this discussion if you didn't even plan to accept the PR :)

**Comment by marlam** [comment]
I did not plan to not accept the PR, and all this is still open to discussion. I'm not sure if the current state does what you intended to do. Is there something missing? Could something be improved?

**Comment by ArsenicBismuth** [comment]
You do you man, idc anymore.

**Pull request closed without merging**
